export const enterpriseRoles = [
  "super_admin",
  "country_admin",
  "country_user",
  "main_branch_admin",
  "city_branch_admin",
  "accountant",
  "cashier",
  "agent_user",
  "staff_user",
  "auditor_viewer"
] as const;

export type EnterpriseRole = (typeof enterpriseRoles)[number];

export const enterpriseRoleScopes: Record<EnterpriseRole, string> = {
  super_admin: "Global",
  country_admin: "Assigned country",
  country_user: "Assigned country",
  main_branch_admin: "Assigned country main branch",
  city_branch_admin: "Assigned city branch",
  accountant: "Assigned accounting scope",
  cashier: "Assigned cash/payment scope",
  agent_user: "Assigned agent tasks",
  staff_user: "Assigned staff tasks",
  auditor_viewer: "Read-only assigned scope"
};

export const enterpriseRolePermissions: Record<EnterpriseRole, string[]> = {
  super_admin: ["*:*"],
  country_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "countries:read",
    "country_branches:create",
    "country_branches:read",
    "country_branches:update",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:create",
    "users:read",
    "users:update",
    "users:delete",
    "customers:create",
    "customers:read",
    "customers:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "accounts:delete",
    "ledgers:create",
    "ledgers:read",
    "ledgers:update",
    "ledgers:delete",
    "ledgers:post",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:post",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:post",
    "reports:read",
    "reports:export",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "products:delete",
    "product_categories:read",
    "product_categories:create",
    "product_categories:update",
    "product_brands:read",
    "product_brands:create",
    "product_brands:update",
    "product_units:read",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:delete",
    "chs_products:export",
    "banks:create",
    "banks:read",
    "banks:update",
    "warehouses:create",
    "warehouses:read",
    "warehouses:update",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "shipping_records:update",
    "clearing_agents:read",
    "clearing_agent_branches:create",
    "clearing_agent_branches:read",
    "clearing_agent_branches:update",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read",
    "email_management:create",
    "email_management:read",
    "email_management:update",
    "whatsapp:read",
    "whatsapp:create",
    "whatsapp:update",
    "whatsapp:delete",
    "currency_rates:create",
    "currency_rates:read",
    "currency_rates:update",
    "approvals:create",
    "approvals:read",
    "approvals:approve",
    "financial_periods:create",
    "financial_periods:read",
    "financial_periods:update"
  ],
  country_user: [
    "dashboard:read",
    "countries:read",
    "country_branches:read",
    "city_branches:read",
    "users:read",
    "customers:read",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "ledgers:create",
    "ledgers:read",
    "ledgers:update",
    "roznamcha:create",
    "roznamcha:read",
    "reports:read",
    "reports:export",
    "purchases:read",
    "products:read",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "chs_products:read",
    "warehouses:read",
    "inventory:read",
    "sales:read",
    "shipping_records:read",
    "messages:read",
    "email_management:read"
  ],
  main_branch_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "countries:read",
    "country_branches:read",
    "city_branches:create",
    "city_branches:read",
    "users:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "ledgers:create",
    "ledgers:read",
    "ledgers:update",
    "financial_periods:read",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:post",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "products:delete",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:export",
    "banks:read",
    "warehouses:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "shipping_records:update",
    "clearing_agent_branches:read",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read",
    "email_management:create",
    "email_management:read",
    "email_management:update",
    "whatsapp:read",
    "whatsapp:create",
    "whatsapp:update",
    "whatsapp:delete",
    "currency_rates:create",
    "currency_rates:read",
    "approvals:create",
    "approvals:read",
    "reports:read"
  ],
  city_branch_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "city_branches:read",
    "users:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "ledgers:create",
    "ledgers:read",
    "ledgers:update",
    "transactions:create",
    "transactions:read",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:post",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "products:delete",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:export",
    "banks:read",
    "warehouses:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "assignments:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read",
    "email_management:create",
    "email_management:read",
    "email_management:update",
    "whatsapp:read",
    "whatsapp:create",
    "whatsapp:update",
    "whatsapp:delete",
    "currency_rates:create",
    "currency_rates:read",
    "approvals:create",
    "approvals:read",
    "reports:read"
  ],
  accountant: [
    "companies:read",
    "accounts:create",
    "accounts:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:post",
    "ledgers:read",
    "financial_periods:read",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:post",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "products:delete",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:export",
    "banks:read",
    "warehouses:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "currency_rates:create",
    "currency_rates:read",
    "currency_rates:update",
    "approvals:create",
    "approvals:read",
    "approvals:approve",
    "reports:read"
  ],
  cashier: [
    "companies:read",
    "country_branches:read",
    "city_branches:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "accounts:read",
    "ledgers:read",
    "currency_rates:read",
    "transactions:create",
    "transactions:read",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:post"
  ],
  agent_user: [
    "transactions:create",
    "transactions:read",
    "customers:create",
    "customers:read",
    "companies:read",
    "shipping_records:create",
    "shipping_records:read",
    "clearing_agent_branches:read",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "messages:create",
    "messages:read",
    "whatsapp:read",
    "whatsapp:create"
  ],
  staff_user: ["transactions:create", "transactions:read", "customers:read", "companies:read", "shipping_records:read", "whatsapp:read"],
  auditor_viewer: ["reports:read", "audit_logs:read", "ledgers:read", "companies:read"]
};

export const dashboardByRole: Record<EnterpriseRole, string> = {
  super_admin: "/dashboard/super-admin",
  country_admin: "/dashboard/country",
  country_user: "/dashboard/country",
  main_branch_admin: "/dashboard/city",
  city_branch_admin: "/dashboard/city",
  accountant: "/dashboard/city",
  cashier: "/dashboard/city",
  agent_user: "/dashboard/agent",
  staff_user: "/dashboard/city",
  auditor_viewer: "/dashboard/reports"
};
