export const resources = [
  "companies",
  "business_groups",
  "country_company_profiles",
  "branches",
  "countries",
  "country_branches",
  "city_branches",
  "clearing_agents",
  "clearing_agent_branches",
  "users",
  "roles",
  "accounts",
  "journal_entries",
  "ledger",
  "ledgers",
  "roznamcha",
  "transactions",
  "purchases",
  "sales",
  "bookings",
  "customers",
  "banks",
  "warehouses",
  "currency_rates",
  "reports",
  "global_reports",
  "products",
  "product_categories",
  "product_brands",
  "product_units",
  "inventory",
  "assignments",
  "record_transfers",
  "inter_branch_transfers",
  "messages",
  "email_management",
  "shipping_records",
  "attachments",
  "settings",
  "audit_logs",
  "chs_products"
] as const;

export const actions = ["create", "read", "update", "delete", "post", "approve", "export"] as const;

export type Resource = (typeof resources)[number];
export type PermissionAction = (typeof actions)[number];

export type Permission = `${Resource}:${PermissionAction}`;

export const allSystemPermissions = resources.flatMap((resource) =>
  actions.map((action) => `${resource}:${action}` as Permission)
);

export const systemRoles = {
  superAdmin: allSystemPermissions,
  countryAdmin: [
    "countries:read",
    "business_groups:read",
    "country_company_profiles:read",
    "country_branches:read",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:read",
    "users:update",
    "transactions:read",
    "currency_rates:create",
    "currency_rates:read",
    "reports:read",
    "reports:export",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read",
    "email_management:create",
    "email_management:read",
    "email_management:update",
    "purchases:read",
    "purchases:create",
    "purchases:update",
    "purchases:delete",
    "purchases:post",
    "roznamcha:read",
    "roznamcha:create",
    "roznamcha:update",
    "roznamcha:post",
    "ledgers:read",
    "ledgers:create",
    "accounts:read",
    "accounts:create",
    "accounts:update",
    "journal_entries:read",
    "journal_entries:create",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read"
  ],
  branchAdmin: [
    "countries:read",
    "business_groups:read",
    "country_company_profiles:read",
    "country_branches:read",
    "city_branches:read",
    "users:read",
    "transactions:create",
    "transactions:read",
    "transactions:post",
    "reports:read",
    "assignments:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read",
    "email_management:create",
    "email_management:read",
    "email_management:update",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:delete",
    "chs_products:export",
    "purchases:read",
    "purchases:create",
    "purchases:update",
    "purchases:delete",
    "purchases:post",
    "roznamcha:read",
    "roznamcha:create",
    "roznamcha:update",
    "roznamcha:post",
    "ledgers:read",
    "ledgers:create",
    "accounts:read",
    "accounts:create",
    "accounts:update",
    "journal_entries:read",
    "journal_entries:create",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read"
  ],
  staff: [
    "countries:read",
    "city_branches:read",
    "transactions:create",
    "transactions:read"
  ],
  owner: [
    "companies:read",
    "branches:read",
    "users:read",
    "users:update",
    "roles:read",
    "roles:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read",
    "reports:read",
    "reports:export",
    "attachments:create",
    "attachments:read",
    "chs_products:create",
    "chs_products:read",
    "chs_products:update",
    "chs_products:delete",
    "chs_products:export"
  ],
  accountant: [
    "branches:read",
    "accounts:read",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read",
    "reports:read",
    "attachments:create",
    "attachments:read"
  ],
  viewer: ["branches:read", "accounts:read", "journal_entries:read", "ledger:read", "reports:read"]
} satisfies Record<string, Permission[]>;

export function hasPermission(grants: Permission[], permission: Permission) {
  const [resource] = permission.split(":");
  return grants.includes(permission) || grants.includes(`${resource}:*` as Permission) || grants.includes("*:*" as Permission);
}
